version: "3.9"
services:
  nginx:
    image: nginx:1.19.10
    ports:
      - "443:443"
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/cert:/etc/nginx/cert
