# fly.toml app configuration file generated for johan-li on 2025-01-03T20:14:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'johan-li'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  build-target = 'runner'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
    # https://fly.io/docs/reference/configuration/#services-ports-http_options-response-pristine
    # This removes a few unnecessary Fly headers
    http_options = { response = { pristine = true } }

  [[services.ports]]
    port = 80
    handlers = ['http']
    # https://community.fly.io/t/cloudflare-525-error-randomly-occurs/1798/44
    # https://community.fly.io/t/cloudflare-525-error-randomly-occurs/1798/45
    # It has to do with fly.io's shared IPv4 and proxying the traffic through Cloudflare
    force_https = false
    http_options = { response = { pristine = true } }

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
