- import_tasks: setup.yml

# https://nextjs.org/docs/deployment#docker-image
# https://github.com/vercel/next.js/issues/5512
- name: deploy build
  synchronize:
    src: "{{ playbook_dir }}/../"
    dest: /home/{{ USER }}/{{ DOMAIN }}/
    rsync_opts:
      - "--include=/public/"
      - "--include=/public/**"
      - "--include=/.next/"
      - "--include=/.next/**"
      - "--include=/.next.config.js"
      - "--include=/node_modules/"
      - "--include=/node_modules/**"
      - "--include=/package.json"
      - "--exclude=*"
      - "--delete-excluded"
  notify:
    - restart service

- name: deploy fingerprint-scanner-simulator
  synchronize:
    src: "{{ playbook_dir }}/../fingerprint-scanner-simulator/build/"
    dest: /home/{{ USER }}/fingerprint-scanner-simulator/
    rsync_opts:
      - "--delete"
  notify:
    - restart service

- name: deploy uncharted-waters-2
  synchronize:
    src: "{{ playbook_dir }}/../uncharted-waters-2/build/"
    dest: /home/{{ USER }}/uncharted-waters-2/
    rsync_opts:
      - "--delete"
  notify:
    - restart service

- name: set permissions
  file:
    dest: /home/{{ USER }}/{{ DOMAIN }}/
    recurse: yes
    owner: "{{ USER }}"
    group: "{{ USER }}"
