- name: check if server has been set up
  stat:
    path: /etc/systemd/system/{{ domain }}.service
  register: result

- import_tasks: setup.yml
  when: result.stat.exists == false

- name: deploy build
  synchronize:
    src: ../build/
    dest: /home/{{ user }}/{{ domain }}/
    delete: yes

- name: set permissions on build
  file:
    dest: /home/{{ user }}/{{ domain }}/
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"

- name: restart service
  systemd:
    name: "{{ domain }}"
    daemon_reload: true
    enabled: yes
    state: restarted
