# https://github.com/nodesource/distributions
- name: add NodeSource package signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add NodeSource repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nodesource.list
  loop:
    - deb https://deb.nodesource.com/node_13.x bionic main
    - deb-src https://deb.nodesource.com/node_13.x bionic main

# https://nginx.org/en/linux_packages.html
- name: add nginx package signing key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- name: add nginx repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nginx.list
  loop:
    - deb https://nginx.org/packages/mainline/ubuntu/ bionic nginx
    - deb-src https://nginx.org/packages/mainline/ubuntu/ bionic nginx

- name: install nodejs, git, nginx, ntp, certbot
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    force_apt_get: yes
  vars:
    packages:
      - nodejs
      - git
      - nginx
      - ntp
      - certbot

- name: setup let's encrypt certificate
  command:
    cmd: |
      certbot certonly --standalone --noninteractive --agree-tos
      --email johan@johanli.com -d {{ domain }}
      --pre-hook "service nginx stop" --post-hook "service nginx start"
    creates: /etc/letsencrypt/live/johan.li/privkey.pem

- name: verify that renewal works
  command:
    cmd: certbot renew --dry-run
    creates: .letsencrypt-renew.skip

- name: delete default server block
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: add server block
  template:
    src: ./server-block.conf
    dest: /etc/nginx/conf.d/{{ domain }}.conf

- name: restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: create group
  group:
    name: "{{ user }}"
    state: present

- name: create user
  user:
    name: "{{ user }}"
    group: "{{ user }}"

- name: create service
  template:
    src: ./systemd.service
    dest: /etc/systemd/system/{{ domain }}.service
