name: 'Run tests'
on: ['push']

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout ${{ github.repository }}'
        uses: 'actions/checkout@v2'
      - name: Run tests
        run: |
          npm ci
          npm test
          npm run test:tsc
          npm run test:lint
